# Generated by Django 5.1.2 on 2024-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
